repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        name: ruff format
        entry: ruff format .
        language: system
        types_or: [python, pyi]
      - id: ruff
        name: ruff check
        entry: ruff check --fix
        language: system
        types_or: [python, pyi]
